#!/usr/bin/env bash
# Generate a Mermaid dependency graph for the current repo. Never hand-draw these.
#   diagram-deps                      write docs/diagrams/dependencies.mmd
#   diagram-deps --check              exit 1 if the committed file is stale (for CI)
#   diagram-deps -o other.mmd         choose the output file
#   diagram-deps -- --collapse 2      pass extra flags to dependency-cruiser (JS/TS only)
# JS/TS → dependency-cruiser · Python with tach.toml → tach · other Python → pyreverse
set -euo pipefail

OUT=docs/diagrams/dependencies.mmd; CHECK=; EXTRA=()
while [ $# -gt 0 ]; do
  case $1 in
    --check) CHECK=1 ;;
    -o) OUT=$2; shift ;;
    --) shift; EXTRA=("$@"); break ;;
    *) echo "unknown option: $1"; exit 1 ;;
  esac
  shift
done

ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$ROOT"
[ -s "$HOME/.nvm/nvm.sh" ] && . "$HOME/.nvm/nvm.sh" >/dev/null 2>&1
export PATH="$HOME/.local/bin:$PATH"
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
GEN="$TMP/deps.mmd"

if [ -f package.json ] || [ -f tsconfig.json ]; then
  # Prefer the project's own dependency-cruiser (it sees the project's TypeScript); fall back to the global one.
  DC=depcruise; [ -x node_modules/.bin/depcruise ] && DC=node_modules/.bin/depcruise
  SRC=.; [ -d src ] && SRC=src
  ARGS=(-x '(^|/)(node_modules|dist|build|coverage|\.next|\.turbo)/' -T mermaid)
  if ls .dependency-cruiser.* >/dev/null 2>&1; then :; else ARGS+=(--no-config); fi
  [ -f tsconfig.json ] && ARGS+=(--ts-config tsconfig.json)
  "$DC" "$SRC" "${ARGS[@]}" ${EXTRA[@]+"${EXTRA[@]}"} 2>/dev/null > "$GEN.body"
  TOOL="dependency-cruiser ($SRC)"
elif [ -f tach.toml ]; then
  tach show --mermaid -o "$GEN.body" >/dev/null 2>&1
  TOOL="tach"
elif [ -f pyproject.toml ] || [ -f setup.py ] || ls ./*.py src/*/__init__.py >/dev/null 2>&1; then
  # Top-level packages only (./pkg or src/pkg); pyreverse walks the sub-packages itself
  PKGS=$({ ls -d ./*/__init__.py src/*/__init__.py 2>/dev/null || true; } | xargs -n1 dirname 2>/dev/null | grep -vE '/(node_modules|\.)' || true)
  [ -n "$PKGS" ] || { echo "No Python packages (folders with __init__.py) found."; exit 1; }
  (cd "$TMP" && uvx --quiet --from pylint pyreverse -o mmd -p deps $(cd "$ROOT" && for p in $PKGS; do printf '%s ' "$ROOT/$p"; done) >/dev/null)
  mv "$TMP/packages_deps.mmd" "$GEN.body"
  TOOL="pyreverse"
else
  echo "No JS/TS or Python project found in $ROOT."; exit 1
fi

[ -s "$GEN.body" ] || { echo "The graph came out empty. For TS, make sure the project uses TypeScript 5 (dependency-cruiser doesn't support TS 7 yet)."; exit 1; }
{ echo "%% Generated by diagram-deps with $TOOL. Do not edit; run diagram-deps to update."; cat "$GEN.body"; [ -n "$(tail -c1 "$GEN.body")" ] && echo; } > "$GEN"

SIZE=$(wc -c < "$GEN" | tr -d ' ')
[ "$SIZE" -gt 50000 ] && echo "Warning: $SIZE characters, over Mermaid's 50,000 limit. Try: diagram-deps -- --collapse 2" >&2

if [ -n "$CHECK" ]; then
  if diff -q "$GEN" "$OUT" >/dev/null 2>&1; then echo "dependency diagram is up to date"; else echo "$OUT is stale: run diagram-deps and commit it"; exit 1; fi
else
  mkdir -p "$(dirname "$OUT")"; cp "$GEN" "$OUT"; echo "wrote $OUT ($TOOL, $SIZE chars)"
fi
